version: '3'
services:
  m2m:
    build:
      context: ..
      args:
        - docEnv= ${docEnv}
    image: m2m:1.0
    container_name: m2m
    depends_on:
      - mosquitto
      - ha
    volumes:
      - ../src:/usr/local/src

  ha:
    image: "homeassistant/home-assistant:0.114.4"
    container_name: ha
    ports:
      - "20805:8123"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/root/ha_env/haconfig/:/config"
      - "/dev/ttyS11:/dev/ttyS11"
    depends_on:
      - mosquitto

  mosquitto:
    image: "eclipse-mosquitto"
    container_name: mosquitto
    ports:
      - "1883:1883"