version: '3'
services:
  m2m:
    image: dockerhub.nlecloud.com/1x_virtual_platform/m2m:1.0.0
    container_name: m2m
    depends_on:
      - mosquitto
      - ha
    volumes:
      - ../config/config.xml:/usr/local/src/config.xml

  ha:
    image: "dockerhub.nlecloud.com/1x_virtual_platform/ha:0.114.4"
    container_name: ha
    ports:
      - "20805:8123"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/root/ha_env/haconfig/:/config"
      - "/dev/ttyS11:/dev/ttyS11"
    depends_on:
      - mosquitto

  mosquitto:
    image: "dockerhub.nlecloud.com/1x_virtual_platform/mosquitto:v1.0.0"
    container_name: mosquitto
    ports:
      - "20905:1883"